# Generated by Django 5.0.14 on 2026-02-05 20:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Admin'), ('bibliotecario', 'Bibliotecario'), ('visitante', 'Visitante')], default='visitante', max_length=20, verbose_name='Rol')),
                ('biblioteca_publica', models.BooleanField(default=False, help_text='Si está marcado, otros usuarios podrán ver tu biblioteca', verbose_name='Biblioteca Pública')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(blank=True, help_text='Código ISBN de 10 o 13 dígitos', max_length=13, null=True, verbose_name='ISBN')),
                ('editorial', models.CharField(blank=True, max_length=200, verbose_name='Editorial')),
                ('año_publicacion', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de Publicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Portada')),
                ('numero_paginas', models.IntegerField(blank=True, null=True, verbose_name='Número de Páginas')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('como_nuevo', 'Como Nuevo'), ('usado_bueno', 'Usado - Buen Estado'), ('usado_aceptable', 'Usado - Aceptable'), ('deteriorado', 'Deteriorado')], default='usado_bueno', max_length=20, verbose_name='Estado')),
                ('formato', models.CharField(choices=[('tapa_dura', 'Tapa Dura'), ('tapa_blanda', 'Tapa Blanda'), ('bolsillo', 'Bolsillo'), ('ebook', 'eBook'), ('audiolibro', 'Audiolibro')], default='tapa_blanda', max_length=20, verbose_name='Formato')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('notas', models.TextField(blank=True, help_text='Razones para adquirir este libro, dónde encontrarlo, etc.', verbose_name='Notas')),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=2, verbose_name='Prioridad')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_deseos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de Deseos',
                'verbose_name_plural': 'Listas de Deseos',
                'ordering': ['-prioridad', '-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prestatario', models.CharField(max_length=200, verbose_name='Nombre del Prestatario')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de Préstamo')),
                ('fecha_devolucion_esperada', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Esperada')),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='biblioteca.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Puntuación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_lectura', models.DateField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='biblioteca.libro', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
            },
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Bibliotecario')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.libro', verbose_name='Libro de Interés')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Contacto',
                'verbose_name_plural': 'Solicitudes de Contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
